### ISSUE TITLE
Z Day!

### ISSUE THREAD

**Issue by impromptuu** [gr33nd3v1l/PKDB#2]
A day for Z-move using Pokemon.  ie. Z-Solarbeam Heatran.  Eeveeboost. z-conversion Porygon-Z. z-hyperbeam porygonz. Z-fly things?

Just a suggestion.  Love your giveaways.

**Comment by gr33nd3v1l** [comment]
Sounds great!

List the pokemon you'd like to see in that day under here!

**Comment by EsmeeInWonderland** [comment]
Suggestions in line with the original suggestion ;)
Eevee @ Eevium Z, Ability: Adaptability, Nature: Jolly, EVs 252 HP / 4 Def / 252 Spe.
- Last Resort (Z-move +2 to all stats)
- Protect
- Baton Pass
- Any (Return/Double-edge/Helping Hand or even some random egg-move)

Persian-A @ Darkium Z, Ability: Fur Coat, Nature: Timid, EVs: 228 HP / 28 Def / 252 Spe IV: 0 Atk
- Parting Shot (Z-move restores HP of the Pokemon switching in)
- Foul Play
- Taunt
- Toxic

Porygon-Z @ Normalium Z, Ability: ?? (Adaptability I guess) Nature: Timid, EVs: 4 HP / 252 SpA / 252 Spe
- Shadow Ball
- Signal Beam
- Nasty Plot
- Conversion (Z-move +1 to all stats)
Note: 31/31/30/30/30/30 for Hidden Power Fighting alternative IIRC, but already given away before, other popular types (such as thunderbolt) are easy TM-able.

Azumarill @ Normalium Z, Ability: Huge Power, Nature: Jolly, EVs: 4HP / 252 Atk / 252 Spe
- Belly Drum (Restores users HP before Belly Drum)
- Play Rough
- Aqua Jet
- Knock Off

Suggestions from Lolisquad:
Lunala @ Psychium Z, Ability: Shadow Shield, Nature: Modest, EVs 4 HP / 252 SpA / 252 Spe
- Hypnosis (+1 speed with Z-move)
- Calm Mind
- Moongeist Beam
- Focus Blast
Note: If possible, PP-up this one in the gen. ;)

Xukritree @ Electrium Z, Ability: Beast Boost, Nature: Timid, EVs: 4 Def / 252 SpA / 252 Spe
- Electric Terrain
- Thunderbolt
- Energy Ball
- Hidden Power (Ground / Ice)
Note: Lolisquad would prefer ground. :) 

Greninja @ Normalium Z, Ability: Protean, Nature: Naive, EVs: 4 Atk / 252 SpA / 252 Spe
- Happy Hour (+1 to all stats)
- Gunk Shot
- Ice Beam
- Low Kick
Note: Cinema Event only, so it can't be shiny. Comes in a Cherish ball. http://www.serebii.net/events/dex/658.shtml

Writing out the Z-Heatran since it was mentioned:
Heatran @ Grassium Z, Ability: Flash Fire, Nature: Timid, EVs: 252 SpA / 4 SpeD / 252 Spe (IVs 0 Atk)
- Solar Beam
- Fire Blast
- Flash Cannon
- Earth Power

Some quirky ones:
Espeon @ Normalium Z, Ability: Magic Bounce, Nature: Modest, EVs: 4 Def / 252 SpA / 252 Spe
- Celebrate (+1 to all stats, note: Event Eevelutions only)
- Stored Power
- Dazzling Gleam
- Filler, maybe spread IVs for HP Fire, Shadowball is fine too.
Note: Birthday event only, can't be shiny, comes in Cherish ball. http://www.serebii.net/events/dex/196.shtml

Whimsicott @ Darkium Z, Ability: Prankster, Nature: Timid, EVs: 252 HP / 4 SpD / 252 Spe
- Memento (Z-move restores HP of pokemon switching in)
- Tailwind
- Taunt
- Encore

Krookodile @ Normalium Z, Ability: Moxie, Nature: Jolly, EVs: 252 Atk / 4 Def / 252 Spe
- Me First
- Knock Off / Power Trip
- Earthquake
- Superpower / Power Trip

Jynx @ Normalium-Z, Ability: Dry Skin, Nature: Timid, EVs: 4 HP / 252 SpA / 252 Spe
- Lovely Kiss (+1 Speed, better accuracy than Hypnosis)
- Nasty Plot
- Ice Beam
- Psyshock / Sub

Darmanitan @ Normalium Z, Ability: Sheer Force, Nature: Jolly, EVs: 252 Atk / 4 ?? / 252 Spe
- Yawn (+1 Speed)
- Flare Blitz
- Rock Slide
- Earthquake

I didn't include pokemon that simply boost an already strong attack to pack even more of a punch, since those sets are usually identical to Choice/Orb sets. Good fillers however include: Kartana, Breloom, Landorus-T, Tailglow Xurkitree, Excadrill, **Garchomp**, Krookodile, **Heatran**, Mimikyu, Aegislash, **Dragonite**, **Gyarados**, Arcanine, Volcarona, Pheromosa, **Celesteela**.

Notes: Garchomp can effectively boost a relatively weak fire-attack, Heatran, Dragonite and Gyarados turn 2-turn moves into a single turn. Celesteela would run it with an uncommong Autotomize sweeper set-up (instead of specially defensive.) Hence I'd add those if any, I'll write out the sets if you'd like me to. :)

Have your pick :D 

PS: Items like Golden Bottle Caps, Lucky Eggs and Apricorn balls fit perfectly ;) ;)

**Comment by gr33nd3v1l** [comment]
I got a Chomp set, could you work out the rest you mentioned? I trust you more with competitive picks than my googleskills

**Comment by impromptuu** [comment]
Those are some great sets.  I might add:
Arcanine @ Firium Z
Ability: Intimidate
EVs: 148 HP / 4 Def / 164 SpA / 28 SpD / 164 Spe
Timid Nature (0 Atk IVs)
- Burn Up
- Snarl
- Protect
- Will-o-Wisp/ Helping Hand

**Comment by impromptuu** [comment]
Torkoal @ Firium Z
Ability: Drought
EVs: 252 HP / 4 Def / 252 SpA
Quiet Nature (0 Spe IVs)
- Eruption
- Heat Wave
- Hidden Power (Ice)
- Protect

**Comment by gr33nd3v1l** [comment]
Jynx @ Normalium-Z, Ability: Dry Skin, Nature: Timid, EVs: 4 HP / 252 SpA / 252 Spe

- Lovely Kiss (+1 Speed, better accuracy than Hypnosis)
- Nasty Plot
- Energy Ball
- Focus Blast
-  Psyshock _relearn_
-  Ice Beam _relearn_
-  Substitute _relearn_
