### ISSUE TITLE
Mod Favorite Day

### ISSUE THREAD

**Issue by BPMCarl** [gr33nd3v1l/PKDB#3]
All Pokemon that day are picked by the Twitch chat Mods and Gr33n too. Their movesets and stats could be chosen by the mods themselves, or just taken from Smogon.

**Comment by BPMCarl** [comment]
Or, they could pick one favorite Pokemon from each gen and have them included every day for a week.

**Comment by Ballerium86** [comment]
My Gen 1 favorite:

Ninetails @ Life Orb

Ability: Drought 
Nature: Timid 
EV's: 252 spA, 4 spD, 252 spe

Moveset:

-Nasty Plot
-Fire Blast 
-Energy Ball
-Substitute

**Comment by Ballerium86** [comment]
If you could make it a female and put it in a luxury ball that would be awesome <3

**Comment by EsmeeInWonderland** [comment]
You basically asked me to pick my favourite child... and I have more than the average Ditto. :'( So a couple of suggestions if Green feels like making me happy. :D 

Gen 1: Clefairy, Vulpix, ♦Ninetales, ♦Persian, Arcanine, Chansey, Dewgong, ♦Haunter, Eevee, Flareon (Mew) 
Gen 2: Belossom, Azumarill, Scizor, ♦Houndoom, ♦Blissey
Gen 3: Blaziken, Mawile, Altaria, Milotic, Banette
Gen 4: Roserade, Lopunny, Lucario, (♦)Weavile, Gliscor, ♦Froslass, (all event-mons, except Arceus)
Gen 5: ♦ Zorua, (Meloetta)
Gen 6: (♦)Greninja, Aegislash, ♦Meowstic M/F, (Diance) 
Gen 7: (♦)A. Ninetales, ♦Ribombee, Lycanroc (Midday) A. Marowak, Toxapex, ♦Salazzle, Tsareena, Mimikyu (I'm only human) Tapu Lele (Magearna)

♦ means I prefer shiny, (♦) means I like either and no icon means please no shiny. :D Ahem, anyway if I'd had to chose for now I'd go for either

Shiny Zorua, Lv. 99, Luxery Ball, I guess... If only Moonball Zorua was legit *cries* @ Life Orb Nickname: Echo
Ability: Illusion
Nature: Timid
EVs: 252 SpA / 4 SpD / 252 Spe (for those evolving it in Zoroark this would be best :D)
- Nasty Plot
- Dark Pulse
- Hidden Power Fighting
- Extrasensory
If possible on relearn (if not put any of the above in relearn) Trick (Move Tutor) for easier transfer into Zoroark for those who'd like to evolve it. Sludge Bomb is sadly an Event move in an ugly ultraball. ;)

(Non-shiny) A. Ninetales, Loveball @ Light Clay Nickname: Ylevil
Ability: Snow Warning
Nature: Timid
EVs: 252 SpA, 4 SpD, 252 Spe
- Aurora Veil
- Encore
- Freeze-dry
- Moonblast
Note: Last 3 are egg-moves that'd be nice to have without relearn. Other popular options are either TMs (Blizzard, Protect) or Vulpix relearns (Icy Wind)

**Comment by gr33nd3v1l** [comment]
I think we'll do 2 per gen per mod

**Comment by Ballerium86** [comment]
Okay, so I've finally managed to narrow down my picks to 2 per generation. Below is my finalized list. Since Sun/Moon is actually my first pokemon game, I have not had as much experience playing around with different sets as some of you probably have, aside from seeing opponent sets in Battle Tree. So with that said, I had to use Smogon for a good many of these. If anyone has any suggestions for improvement, please feel free to chime in. :)

**Generation 1**

_1. Ninetails (F) @ Life Orb_

Level: 100
Shiny: Yes
Ball: Luxury

Abiity: Drought
Nature: Timid
EV's: 252 SpA / 4 SpD / 252 Spe

Moveset

- Nasty Plot
- Fire Blast
- Energy Ball
- Substitute

_2. Sandslash (M) @ Life Orb_

Level: 100
Shiny: Yes
Ball: Luxury

Ability: Sand Rush
Nature: Jolly
EV's: 252 Atk / 4 Def / 252 Spe

Moveset

- Swords Dance
- Stone Edge
- Knock Off
- Earthquake

**Generation 2**

_1. Politoed (F) @ Leftovers_

Level: 100
Shiny: Yes
Ball: Heal

Ability: Drizzle
Nature: Modest
EV's: 248 HP / 8 Def / 252 SpA

Moveset

- Scald
- Ice Beam
- Hidden Power (Electric)
- Encore

_2. Porygon2 @ Eviolite_

Level:100
Shiny: Yes
Ball: Lure

Ability: Download
Nature: Calm
EV's: 252 HP / 130 Def / 126 SpD

Moveset

- Recover
- Tri Attack
- Ice Beam
- Toxic

**Generation 3**

_1. Ludicolo (M) @ Leftovers_

Level: 100
Shiny: Yes
Ball: Net

Ability: Rain Dish
Nature: Sassy
EV's: 252 HP / 146 Def / 110 SpD

Moveset

- Fake Out
- Leech Seed
- Giga Drain
- Toxic

_2. Manectric (M) @ Manectite (when available) / Life Orb_

Level: 100
Shiny: Yes
Ball: Quick

Ability: Lightning Rod
Nature: Timid
EV's: 252 SpA / 4 Def / 252 Spe

Moveset

- Volt Switch
- Thunderbolt
- Flamethrower
- Hidden Power (Ice)

**Generation 4**

_1. Spiritomb (F) @ Black Glasses_

Level: 100
Shiny: Yes
Ball: Heal

Ability: Infiltrator
Nature: Adamant
EV's: 212 HP / 252 Atk / 44 Spe

Moveset

- Sucker Punch
- Pursuit
- Taunt
- Will-O-Wisp

_2. Gastrodon - West Sea (F) @ Leftovers_

Level: 100
Shiny: Yes
Ball: Nest

Ability: Storm Drain
Nature: Bold
EV's: 252 HP / 244 Def / 12 Spe

Moveset

- Scald
- Earth Power
- Toxic
- Recover

**Generation 5**

_1. Liepard (F) @ Black Glasses_

Level: 100
Shiny: Yes
Ball: Luxury

Ability: Prankster
Nature: Timid
EV's: 252 SpA / 4 Def / 252 Spe

Moveset

- Nasty Plot
- Snarl
- Dark Pulse
- Encore

_2. Chandelure (F) @ Leftovers_

Level: 100
Shiny: Yes
Ball: Luxury

Ability: Flash Fire
Nature: Timid 
EV's: 252 SpA / 4 SpD / 252 Spe

Moveset

- Substitute
- Calm Mind
- Flamethrower
- Shadow Ball

**Generation 6**

_1. Noivern (M) @ Life Orb_

Level: 100
Shiny: Yes
Ball: Premier

Ability: Infiltrator
Nature: Timid
EV's: 252 SpA / 4 SpD / 252 Spe

Moveset

- Draco Meteor
- Flamethrower
- Boomburst
- Hurricane

_2. Florges (F) @ Grassium Z / Leftovers_

Level: 100
Shiny: Yes
Ball: Heal

Ability: Flower Veil
Nature: Bold
EV's: 252 HP / 252 Def / 4 SpD

Moveset

- Grassy Terrain
- Giga Drain
- Misty Terrain
- Dazzling Gleam

**Generation 7**

_1. Togedemaru (M) @ Rocky Helmet_

Level: 100
Shiny: Yes
Ball: Fast

Ability: Lightning Rod
Nature: Adamant
EV's: 252 Atk / 4 Def / 242 Spe

Moveset

- Wild Charge
- Fell Stinger
- Spiky Shield
- Reflect

_2. Nihilego @ Focus Sash_

Level: 100
Shiny: No
Ball: Beast

Ability: Beast Boost
Nature: Timid
EV's: 252 SpA / 4 Def / 252 Spe

Moveset

- Toxic Spikes
- Power Gem
- Sludge Wave
- Hidden Power (Ice)

***Note: I may have screwed up on some of the EV's as I'm still pretty much a noob at distributing them. So if something looks a little wonky or is impossible, please feel free to fix it to what you think would be best. Sorry!

**Comment by EsmeeInWonderland** [comment]
I'll look into some sets later today (I hope) I think I'll go for:
Gen 1: Clefairy, Persian (maybe Dewgong instead)
Gen 2: Belossom, Scizor, (maybe ♦Blissey instead)
Gen 3: Altaria, Banette
Gen 4: Roserade ♦Froslass (maybe Weavile instead)
Gen 5: ♦ Zorua (Zorua and Meloetta are the only ones I seem to like from this gen? XD)
Gen 6: ♦Meowstic M/F
Gen 7: (♦)A. Ninetales, ♦Ribombee (maybe ♦Salazzle, need a sec to look at sets)

We could just pretend Weavile is gen 5 for a day. Keepo. And uhm, Lucario makes it to fighting day right? ^^"

**Comment by EsmeeInWonderland** [comment]
**Gen 1:**
Non-shiny Persian @ Life Orb (Female in a Loveball with the nickname: Nala)
Ability: Technician
Nature: Timid
EVs: 4 Def/ 252 SpA / 252 Spe
- Nasty Plot
- Hyper Voice
- Hidden Power (Ghost) 
- Water Pulse

Note: Hyper Voice is a tutor move.

Non-shiny Clefairy @ Eviolite (Female in a Loveball with the nickname: Ribbon)
Ability: Friend Guard
Nature: Sassy
EVs: 252 HP / 140 Def / 116 SpD 
IVs: 0 Atk / 0 Spe
- Follow Me
- After You
- Minimize / Heal Pulse
- Protect

Note: Minimize is a learn move and Heal Pulse an egg move, I'd prefer Minimize in the skill set and Heal Pulse on relearn if it's all the same for genning, if it's more effort just put in Heal Pulse since Minimize is on relearn anyway. 

**Gen 2:**
Non-shiny Bellossom @ Life Orb (Female in a Friendball with the nickname: Lies)
Ability: Chlorophyll
Nature: Modest
EVs 252 SpA / 4 SpD / 252 Spe
- Solar Beam
- Hidden Power Fire
- Moonblast
- Sleep Powder

Non-shiny Scizor @ Any (see notes)
Ability: Light Metal / Technician (see notes)
Nature: Impish
EVs: 248 HP / 116 Def / 128 SpD / 16 Spe
- Bullet Punch
- U-Turn
- Roost
- Swords Dance

Notes: If possible I'd love either a gen 1 (Red) transfer in a Safari Ball (which would make it Light Metal) or the one from this event: http://www.serebii.net/events/dex/123.shtml to get the Cherish Ball (at which point its nickname and ability (Technician) is set.)

**Gen 3:**
Non-shiny Altaria @ Any (Female in a Dive Ball with the nickname: Navi)
Ability: Natural Cure
Nature: Adamant
EVs: 252 Atk / 4 Def / 252 Spe
- Dragon Dance 
- Return
- Earthquake
- Roost

Notes: Nice Tutor moves: Tailwind, Heal Bell, Draco Meteor, Outrage, if they could be on relearn, great! If not, oh well. 

Non-shiny Banette @ any (Female in a Dreamball with the nickname: Ghoulia)
Ability: Insomnia
Nature: Adamant
EVs: 228 HP / 252 Atk / 28 Spe
- Knock Off
- Will-O-Wisp
- Shadow Claw
- Shadow Sneak / Destiny Bond

Notes: Destiny Bond on relearn, or if easier in the skillset since Shadowsneak is always on relearn. Shame Moonball wouldn't be legit :'(

**Gen 4:**
Shiny Froslass @ Focus Sash (Female in a Loveball with the nickname: Rosa)
Ability: Cursed Body
Nature: Timid
EVs: 252 SpA / 4 SpD / 252 Spe
- Spikes
- Taunt
- Icy Wind
- Destiny Bond

Non-Shiny Roserade @ Black Sludge (Female in a Loveball with the nickname: Bloss)
Ability: Natural Cure
Nature: Timid
EVs: 252 SpA / 4 SpD / 252 Spe
- Spikes
- Leaf Storm
- Sludge Bomb
- Hidden Power Fire
Note: Having the egg moves: Extrasensory, Sleep Powder, Giga Drain on relearn would be cool.


**Gen 5:**
Shiny Zorua, Lv. 99 @ Life Orb (Female in a Luxery Ball with the nickname: Echo)
Ability: Illusion
Nature: Timid
EVs: 252 SpA / 4 SpD / 252 Spe 
- Nasty Plot
- Dark Pulse
- Hidden Power Fighting
- Extrasensory
If possible on relearn (if not put any of the above in relearn) Trick (Move Tutor) for easier transfer into Zoroark for those who'd like to evolve it. Sludge Bomb is sadly an Event move in an ugly ultraball. ;)

Volcarona non-shiny in a Premierball, any nickname you can think off :D I'm 99% sure you gave away a perfectly amazing shiny one before, that one will do! If I remember the Volcarona incorrectly copy the Zorua set, evolve it and make it non-shiny? I love that little furball just that much.

**Gen 6:**
Shiny Meowstic @ Life Orb (Female in a Premierball with the nickname: Stippy)
Ability: Competitive
Nature: Timid
EVs: 4 Def / 252 SpA / 252 Spe
- Psychic
- Hidden Power (Fightning)
- Shadow Ball
- Thunder Wave

Shiny Meowstic @ Light Screen (Male in a Premierball with the nickname: Pruts)
Ability: Prankster
Nature: Bold
EVs: 252 HP / 252 Def / 4 SpD
- Psychic
- Reflect
- Light Screen
- Yawn

**Gen 7**
(In Loveball with the nickname: Ylevil)
Ninetales-Alola @ Light Clay Ability: Snow Warning EVs: 4 Def / 252 SpA / 252 Spe Timid Nature
- Aurora Veil
- Freeze-Dry
- Hidden Power Fire
- Encore
Note: Moonblast (eggmove) on relearn or over Hidden Power (can keep the IVs for Hidden Power Fire since it's a TM, just like Blizzard)

(In Loveball with the nickname: Videl)
Salazzle @ Life Orb Ability: Corrosion EVs: 252 SpA / 4 SpD / 252 Spe Timid Nature 
- Nasty Plot 
- Fire Blast
- Sludge Wave
- Hidden Power Ground

Copy pasted the last 2 and Volcarona was also sheer laziness. :(

**Comment by ShapeOfAUnicorn** [comment]
Okay, just saw this. Thanks, @EsmeeInWonderland for calling us lazy mods out. And thanks especially to @BPMCarl, this was a fun idea!

These aren't necessarily the best Pokemon, nor are they the best sets available, but some are for various niche reasons (Battle Tree, Trick Room, etc.). They're more just the Pokemon I really liked the most.


**Gen 1**
Gengar @ PP Max (Mega Gengar) in Dusk Ball
Ability: Cursed Body
Nature: Timid
EVs: 4 Def / 252 SpA / 252 Spe
- Taunt
- Destiny Bond
- Focus Blast
- Sludge Wave (is Sludge Wave possible to keep it legitimate? I think the only way is if it came from Dream World? If not then Shadow Ball works here instead)

Aerodactyl @ Gold Bottle Cap (Mega Aerodactyl) in Heavy Ball
Ability: Unnerve (HA)
Nature: Jolly
EVs: 252 Atk / 4 SpD / 252 Spe
- Stone Edge
- Aerial Ace
- Ice Fang
- Earthquake


**Gen 2**
Tyranitar @ Chople Berry in Dusk Ball
Ability: Sand Stream
Nature: Careful
EVs: 248 HP / 8 Def / 252 SpD
- Stealth Rock
- Pursuit
- Foul Play
- Thunder Wave

Shiny Wobbuffet @ Leftovers in Heal Ball
Ability: Shadow Tag
Nature: Calm
EVs: 204 HP / 32 Def / 252 SpD
- Encore
- Counter
- Mirror Coat
- Safeguard


**Gen 3**
Swampert @ Leftovers in Lure Ball
Ability: Torrent
Nature: Relaxed
EVs: 240 HP / 252 Def / 16 SpD
- Stealth Rock
- Earthquake
- Scald
- Roar

Torkoal @ Charcoal
Ability: Drought
Nature: Quiet
EVs: 252 HP / 4 Def / 252 SpA
IVs: 0 Spe
- Eruption
- Heat Wave
- Hidden Power (Ice)
- Protect


**Gen 4**
Mamoswine @ Life Orb
Ability: Thick Fat
Nature: Naive
EVs: 240 Atk / 16 SpA / 252 Spe
- Icicle Crash
- Earthquake
- Ice Shard
- Freeze-Dry

Infernape @ Life Orb
Ability: Blaze
Nature: Naive
EVs: 168 Atk / 88 SpA / 252 Spe
- Overheat
- Close Combat
- Grass Knot
- Gunk Shot


**Gen 5**
Hydreigon @ Choice Specs
Ability: Levitate
Nature: Timid
EVs: 252 SpA / 4 SpD / 252 Spe
- Dark Pulse
- Draco Meter
- Flash Cannon
- U-Turn

Bisharp @ Life Orb in Fast Ball
Ability: Defiant
Nature: Jolly
EVs: 252 Atk / 4 SpD / 252 Spe
- Knock Off
- Iron Head
- Sucker Punch
- Swords Dance


**Gen 6**
Aegislash @ Leftovers in Luxury Ball
Ability: Stance Change
Nature: Adamant
EVs: 252 HP / 252 Atk / 4 Spe
- King's Shield
- Swords Dance
- Shadow Sneak
- Sacred Sword

Chesnaught @ Leftovers in Nest Ball
Ability: Bulletproof
Nature: Impish
EVs: 252 HP / 252 Def / 4 SpD
- Spikes
- Leech Seed
- Drain Punch
- Spiky Shield


**Gen 7**
Mimikyu @ Life Orb in Dusk Ball
Ability: Disguise
Nature: Jolly
EVs: 252 Atk / 4 SpD / 252 Spe
- Swords Dance
- Play Rough
- Shadow Sneak
- Shadow Claw

Golisopod @ Assault Vest
Ability: Emergency Exit
Nature: Adamant
EVs: 252 HP / 252 Atk / 4 SpD
Adamant Nature
- First Impression
- Liquidation
- Leech Life
- Sucker Punch

**Comment by gr33nd3v1l** [comment]
These need to be tested and replaced if they wont work.    
At the moment, they are flagged illegal.    
 This doesn't mean they can't be made the way you want them, I'm just pointing it out so we have a fallback if they won't work :)

@Ballerium86 

    tomorrow :yawn:

@EsmeeInWonderland - pick for gen5 :)

    Altaria has Tailwind, Heal Bell, Draco Meteor, Outrage on relearn, but needs testing
    Froslass @ Focus Sash Ability: Cursed Body EVs: 252 SpA / 4 SpD / 252 Spe Timid Nature
    - Spikes
    - Taunt
    - Icy Wind
    - Will-O-Wisp
    Zorua has S-Wave and Trick on relearn, needs to be tested
    Meowstic can't be in apricorn ball
    Ninetales-Alola @ Light Clay Ability: Snow Warning EVs: 4 Def / 252 SpA / 252 Spe Timid Nature
    - Aurora Veil
    - Freeze-Dry
    - Hidden Power Fire
    - Encore
    Salazzle @ Life Orb Ability: Corrosion EVs: 252 SpA / 4 SpD / 252 Spe Timid Nature 
    - Nasty Plot 
    - Fire Blast
    - Sludge Wave
    - Hidden Power Ground

@ShapeOfAUnicorn

    Bisharp can't be in apricorn ball
    Swampert can't be in apricorn ball
    Aerodactyl can't be in apricorn ball
    Used JPN event Gengar with SludgeWave

**Comment by BPMCarl** [comment]
All these picks have me excited for the day! Glad you all wanted to participate!

**Comment by ShapeOfAUnicorn** [comment]
D'oh! Didn't even pay attention to the ball situation, was just picking ones I remembered that I thought would look nice with the Pokemon. Apologies there. I'm not a ball purist so I guess since I don't care enough about the balls, I should've just not recommended them.

**Comment by gr33nd3v1l** [comment]
@Ballerium86 

    Ninetales-a will be on Trubbish, yours on Nosepass
    Porygon2 can't be in apricorn ball

**Comment by EsmeeInWonderland** [comment]
Edit: Fixed!

Meowstic to Premierball (both) and the Salazzle and Ninetales sets look fine, though maybe Moonblast (egg-move) on relearn / over Aurora Veil or Hidden Power since they are TMs? Gen 5 uhm... Zoroark or non-shiny Volcarona I guess? ^^" Just w/e set (I think you have a shiny one saved somewhere?)

**Comment by Ballerium86** [comment]
@gr33nd3v1l 

I checked just to be sure and I requested Porygon2 in a Lure ball. But if that won't work, a heal ball, dive ball, or net ball would be cool. ^^ 

If those are all illegal too, then just whatever ball it can go in will be fine. Thank you! <3

**Comment by gr33nd3v1l** [comment]
Porygon2 cant be in apricorn ball

Scizor can't have Light Metal, apparently - keeps calling it illegal

**Comment by Ballerium86** [comment]
So...are the rest of the Mod's Choice pokemon going to be done on another day? I figured it would be today but I see its something different.

FeelsConfusedMan

**Comment by EsmeeInWonderland** [comment]
I think today is the day MasterAndy69 requested and that mod day will continue tomorrow (since Andy spend spots whereas we just got spoiled.) At least I hope so for Ball :( hope Green is alright.

**Comment by Ballerium86** [comment]
Ahhh I see. Makes sense. I remember MasterAndy69 saying something about wanting it today or tomorrow.

Just woke up, brain still foggy XD

Did something happen to Greenie?

**Comment by EsmeeInWonderland** [comment]
Don't know, he might have taken a day off. :D

**Comment by Ballerium86** [comment]
Oh okay. I got worried that something happened when you said you hoped he is okay :(

**Comment by EsmeeInWonderland** [comment]
Sorry, didn't mean to worry you.

**Comment by Ballerium86** [comment]
It's all good :)
