### ISSUE TITLE
Gengar, Absol

### ISSUE THREAD

**Issue by Daviduxtor** [gr33nd3v1l/PKDB#6]
Gengar and Absol please.

**Comment by gr33nd3v1l** [comment]
Looking for sets

**Comment by EsmeeInWonderland** [comment]
Suggested sets if the OP won't bring their own:

Gengar @ Life Orb, Ability: Cursed Body, Nature: Timid, EVs: 4 Def / 252 SpA / 252 Spe
- Sludge Wave
- Shadow Ball
- Focus Blast
- Taunt / Thunderbolt
Notes: Despite Gengar's versitile move options, his EV spread and nature is almost always the one above. On top of that almost all his common abilities are either from TM (Taunt, Focus Blast, Shadow Ball, Substitute, Will-O-Wisp, Thunderbolt) or level-up (Hex, Destiny Bond) the one exceptions is Sludge Wave (a good stab move) which is event only. http://www.serebii.net/events/dex/094.shtml Hence, if possible, I'd try to recreate one of the event ones (my vote goes to NA/EU for name-sakes.) It'd still be shiny. :)

Absol @ Life Orb, Ability: Super Luck (no Mega) / Justified (Mega), Nature: Adamant (no Mega) Jolly (Mega) EVs: 252 Atk / 4 SpD / 252 Spe
- Knock Off
- Superpower  / Play Rough
- Sucker Punch
- Swords Dance
Notes: Quite a few popular moves for Absol are 'special' Knock-off and Superpower (coverage) are from the Move Tutor (PT/HGSS/B2W2/ORAS) Play Rough is an egg move. I'd love an Absol with those 3 options if possible, though if you want it BR you'll likely want either Superpower or Play Rough because of Swords Dance / Sucker Punch.

**Comment by gr33nd3v1l** [comment]
Absol can always have nonBR moves on relearn!

And I know about sludge wave gengar, had my own fair share of difficulties obtaining one back when it was distributed 🗡 

Looks good!

**Comment by Miisha** [comment]
Trick as relearn or over a TM on the gengar would be nice (for scarf sets) :)

**Comment by gr33nd3v1l** [comment]
Need to add to TODO

**Comment by Daviduxtor** [comment]
Add a Vivillon named Satan cause he is the number 666 with the sun pattern

**Comment by Daviduxtor** [comment]
Add accelgor pls
